version: '2.1'
services:

  config:
    environment:
      CONFIG_SERVICE_PASSWORD:             $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:             $CONFIG_SERVICE_DEV_PORT
      AUTH_SERVICE_DEV_PORT:               $AUTH_SERVICE_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:           $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD:    $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:    $CONFIG_SERVICE_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:  $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-point:
    environment:
      CONFIG_SERVICE_PASSWORD:    $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:    $CONFIG_SERVICE_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:  $REGISTRY_SERVICE_DEV_PORT
      AUTH_SERVICE_DEV_PORT:      $AUTH_SERVICE_DEV_PORT
      GATEWAY_SERVICE_DEV_PORT:   $GATEWAY_SERVICE_DEV_PORT
    image: mservicet-gateway-point
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD:              $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:              $CONFIG_SERVICE_DEV_PORT
      ACCOUNT_SERVICE_PASSWORD:             $ACCOUNT_SERVICE_PASSWORD
      AUTH_SERVICE_DEV_PORT:                $AUTH_SERVICE_DEV_PORT
      MONGODB_PASSWORD:                     $MONGODB_PASSWORD
      REGISTRY_SERVICE_DEV_PORT:            $REGISTRY_SERVICE_DEV_PORT
      MONGODB_SERVICE_INTERNAL_DEV_PORT:    $MONGODB_SERVICE_INTERNAL_DEV_PORT
    image: mservicet-auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: mservicet-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD:              $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:              $CONFIG_SERVICE_DEV_PORT
      ACCOUNT_SERVICE_PASSWORD:             $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD:                     $MONGODB_PASSWORD
      ACCOUNT_SERVICE_DEV_PORT:             $ACCOUNT_SERVICE_DEV_PORT
      AUTH_SERVICE_DEV_PORT:                $AUTH_SERVICE_DEV_PORT
      MONGODB_SERVICE_INTERNAL_DEV_PORT:    $MONGODB_SERVICE_INTERNAL_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:            $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-account-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: mservicet-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  arma-service:
    environment:
      CONFIG_SERVICE_PASSWORD:              $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_DEV_PORT:              $CONFIG_SERVICE_DEV_PORT
      ARMA_SERVICE_PASSWORD:                $ARMA_SERVICE_PASSWORD
      MONGODB_PASSWORD:                     $MONGODB_PASSWORD
      ARMA_SERVICE_DEV_PORT:                $ARMA_SERVICE_DEV_PORT
      AUTH_SERVICE_DEV_PORT:                $AUTH_SERVICE_DEV_PORT
      MONGODB_SERVICE_INTERNAL_DEV_PORT:    $MONGODB_SERVICE_INTERNAL_DEV_PORT
      REGISTRY_SERVICE_DEV_PORT:            $REGISTRY_SERVICE_DEV_PORT
    image: mservicet-arma-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  arma-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: mservicet-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  service-viewer:
    image: mservicet-service-viewer
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    logging:
      options:
        max-size: "10m"
        max-file: "10"
