security:
  oauth2:
    client:
      clientId: arma-service
      clientSecret: ${ARMA_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:${AUTH_SERVICE_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /arma-configs
  port: ${ARMA_SERVICE_DEV_PORT}