spring:
  data:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://auth-mysqld:${DEFAULT_MYSQL_DB_PORT}/spring_social?useUnicode=yes&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
      username: a3user
      password: qwerty
      jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true

server:
  servlet:
    context-path: /mservicet
  port: ${AUTH_SERVICE_DEV_PORT}
